package com.jobs.ags.hr.interviewprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CandidateDetail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String name;
	private String isGROApproved;
	private java.lang.String lob;
	private java.lang.String applicationId;

	public CandidateDetail() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getLob() {
		return this.lob;
	}

	public void setLob(java.lang.String lob) {
		this.lob = lob;
	}

	public java.lang.String getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(java.lang.String applicationId) {
		this.applicationId = applicationId;
	}

	public java.lang.String getIsGROApproved() {
		return this.isGROApproved;
	}

	public void setIsGROApproved(java.lang.String isGROApproved) {
		this.isGROApproved = isGROApproved;
	}

	public CandidateDetail(java.lang.String id, java.lang.String name,
			java.lang.String isGROApproved, java.lang.String lob,
			java.lang.String applicationId) {
		this.id = id;
		this.name = name;
		this.isGROApproved = isGROApproved;
		this.lob = lob;
		this.applicationId = applicationId;
	}

}