package com.jobs.ags.hr.interviewprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CandidateDetail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String lob;
	private java.lang.String applicationId;

	private Boolean isGREApproved;

	private java.lang.String jobType;

	private java.lang.String id;

	public CandidateDetail() {
	}

	public java.lang.String getLob() {
		return this.lob;
	}

	public void setLob(java.lang.String lob) {
		this.lob = lob;
	}

	public java.lang.String getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(java.lang.String applicationId) {
		this.applicationId = applicationId;
	}

	public java.lang.Boolean getIsGREApproved() {
		return this.isGREApproved;
	}

	public void setIsGREApproved(java.lang.Boolean isGREApproved) {
		this.isGREApproved = isGREApproved;
	}

	public java.lang.String getJobType() {
		return this.jobType;
	}

	public void setJobType(java.lang.String jobType) {
		this.jobType = jobType;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public CandidateDetail(java.lang.String lob,
			java.lang.String applicationId, java.lang.Boolean isGREApproved,
			java.lang.String jobType, java.lang.String id) {
		this.lob = lob;
		this.applicationId = applicationId;
		this.isGREApproved = isGREApproved;
		this.jobType = jobType;
		this.id = id;
	}

}